[package]
name = "photon"
version = "0.1.0"
authors = ["Newton Ni <nwtnni@gmail.com>"]
edition = "2018"

[features]
default = []
stats = []

[dependencies]
byteorder = "1.3.2"
rand = "0.6.5"
rayon = "1.0.3"
lodepng = "2.4.2"
partition = "0.1.1"
readonly = "0.1.4"
