[package]
name = "photon"
version = "0.1.0"
authors = ["Newton Ni <nwtnni@gmail.com>"]
edition = "2018"

[dependencies]
num-traits = "0.2.6"
noisy_float = "0.1.8"
serde = "1.0"
serde_derive = "1.0"
matrixmultiply = "0.2.2"
rand = "0.6.5"
