[package]
name = "photon"
version = "0.1.0"
authors = ["Newton Ni <nwtnni@gmail.com>"]
edition = "2018"

[features]
default = []
stats = []

[dependencies]
byteorder = "1.3.4"
lodepng = "2.4.2"
partition = "0.1.1"
rand = "0.7.3"
rayon = "1.3.0"
readonly = "0.1.5"

[profile.release]
debug = true
